const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let selected=[], currentAudit=null;
const sampleFallback={businessName:'Sunrise Bakery',score:68,summary:'Your profile looks appealing, but visitors do not get a fast, compelling reason to visit or order. Clearer local positioning and a simpler buying path can turn more profile views into customers.',metrics:[{name:'Profile & bio',score:55},{name:'Content quality',score:81},{name:'Local discovery',score:49},{name:'Conversion',score:62}],problems:[{severity:'High',title:'The bio lacks a clear local promise',evidence:'The offer, neighborhood and reason to choose the business are not immediately clear.',solution:'Lead with the signature product, location and one direct order action.',example:'Fresh pastries baked daily in East Austin 🥐'},{severity:'High',title:'There is no direct order path',evidence:'A general homepage adds steps for mobile visitors who are ready to buy.',solution:'Link directly to pre-orders, WhatsApp or the current menu.',example:'Pre-order tomorrow’s pastry box ↓'},{severity:'Medium',title:'Reels need stronger local discovery signals',evidence:'Product videos are attractive, but hooks and location context are weak.',solution:'Name the city or neighborhood in the opening text, caption and spoken hook.',example:'The croissant East Austin wakes up early for.'}],bio:'East Austin bakery 🥐\nSmall-batch pastries baked fresh daily\nPre-order tomorrow’s box ↓',pillars:[{name:'Product desire',description:'Close-up products, seasonal drops and best sellers'},{name:'Behind the scenes',description:'Baking process, ingredients and morning preparation'},{name:'Local community',description:'Neighborhood stories, events and collaborations'},{name:'Customer proof',description:'Reviews, reactions and customer favorites'}],actions:[{week:'Week 1',title:'Fix the conversion foundation',tasks:['Rewrite the bio','Create Order, Menu and Reviews highlights','Replace the general link with a direct order path']},{week:'Week 2',title:'Build a repeatable content system',tasks:['Choose four content pillars','Film three short product videos in one session','Write local-first hooks for each Reel']},{week:'Week 3',title:'Increase local discovery',tasks:['Collaborate with one nearby business','Publish one neighborhood guide post','Ask five happy customers for tagged stories']},{week:'Week 4',title:'Review and improve',tasks:['Compare saves, shares and profile actions','Repeat the strongest post format','Plan next month from the results']}]};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function filesChanged(files){selected=[...files].filter(f=>f.type.startsWith('image/')).slice(0,6);$('#files').innerHTML=selected.map(f=>`<span class="file">${f.name.replace(/[<>]/g,'')} · ${Math.ceil(f.size/1024)} KB</span>`).join('')}
$('#screenshots').addEventListener('change',e=>filesChanged(e.target.files));
const drop=$('#drop');['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('over')}));['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('over')}));drop.addEventListener('drop',e=>filesChanged(e.dataTransfer.files));
async function dataUrls(){const allowed=selected.filter(f=>f.size<=4*1024*1024);if(allowed.length<selected.length)toast('Images over 4 MB were skipped');return Promise.all(allowed.map(f=>new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})))}
function loading(on){$('#setup').classList.toggle('hidden',on);$('#results').classList.add('hidden');$('#loading').classList.toggle('hidden',!on);if(on){let p=8,i=0;const lines=['Reviewing your profile positioning…','Finding conversion problems…','Building your content strategy…','Prioritizing the 30-day roadmap…'];$('#loadingText').textContent=lines[0];$('#progress').style.width='8%';window.loader=setInterval(()=>{p=Math.min(92,p+Math.random()*16);i=Math.min(3,i+1);$('#progress').style.width=p+'%';$('#loadingText').textContent=lines[i]},750)}else clearInterval(window.loader)}
async function request(body){const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
$('#auditForm').addEventListener('submit',async e=>{e.preventDefault();loading(true);try{const audit=await request({action:'analyze',instagramUrl:$('#instagramUrl').value,businessType:$('#businessType').value,location:$('#location').value,goal:$('#goal').value,images:await dataUrls()});render(audit)}catch(err){loading(false);$('#setup').classList.remove('hidden');toast(err.message)}});
$('#demo').addEventListener('click',async()=>{loading(true);try{render(await request({action:'demo'}))}catch{render(sampleFallback)}});
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(a){currentAudit=a;loading(false);$('#setup').classList.add('hidden');$('#results').classList.remove('hidden');$('#businessName').textContent=a.businessName||'Your business';$('#summary').textContent=a.summary||'';const score=Math.max(0,Math.min(100,Number(a.score)||0));$('#scoreValue').textContent=score;requestAnimationFrame(()=>$('#scoreArc').style.strokeDashoffset=314-(314*score/100));$('#metrics').innerHTML=(a.metrics||[]).map(m=>`<div class="metric"><div class="metricTop"><span>${esc(m.name)}</span><strong>${Number(m.score)||0}</strong></div><div class="bar"><i style="width:${Math.max(0,Math.min(100,Number(m.score)||0))}%"></i></div></div>`).join('');$('#problems').innerHTML=(a.problems||[]).map(p=>`<article class="problem"><div class="severity ${esc(p.severity)}">● ${esc(p.severity)} impact</div><h3>${esc(p.title)}</h3><p>${esc(p.evidence)}</p><div class="solution"><b>Fix:</b> ${esc(p.solution)}</div><p class="example">“${esc(p.example)}”</p></article>`).join('');$('#bio').textContent=a.bio||'';$('#pillars').innerHTML=(a.pillars||[]).map(p=>`<div class="pillar"><b>${esc(p.name)}</b><small>${esc(p.description)}</small></div>`).join('');$('#actions').innerHTML=(a.actions||[]).map(w=>`<div class="week"><div class="weekLabel">${esc(w.week)}</div><div><h3>${esc(w.title)}</h3><ul>${(w.tasks||[]).map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div></div>`).join('');window.scrollTo({top:0,behavior:'smooth'})}
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab))});
$('#newAudit').onclick=()=>{$('#results').classList.add('hidden');$('#setup').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})};
$('.copyBtn').onclick=async()=>{await navigator.clipboard.writeText($('#bio').textContent);toast('Bio copied')};$('#printReport').onclick=()=>window.print();
$('#chatForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#chatInput'),q=input.value.trim();if(!q)return;$('#messages').insertAdjacentHTML('beforeend',`<div class="message user">${esc(q)}</div>`);input.value='';const wait=document.createElement('div');wait.className='message ai';wait.textContent='Thinking…';$('#messages').appendChild(wait);$('#messages').scrollTop=$('#messages').scrollHeight;try{const j=await request({action:'chat',question:q,audit:currentAudit});wait.textContent=j.answer}catch(err){wait.textContent='The AI coach is not configured yet. Add the AI API key in Vercel to activate it.'}
);
